-- Create a small, auto-suspending warehouse (keeps cost near zero)
CREATE WAREHOUSE IF NOT EXISTS SOLAR_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database + schemas
CREATE DATABASE IF NOT EXISTS SOLAR_DB;
CREATE SCHEMA IF NOT EXISTS SOLAR_DB.RAW;
CREATE SCHEMA IF NOT EXISTS SOLAR_DB.MART;

-- Optional: set context for the rest of the session
USE WAREHOUSE SOLAR_WH;
USE DATABASE SOLAR_DB;
USE SCHEMA RAW;

-- (Optional) simple role/user grants – replace <USER_OR_ROLE>
-- GRANT USAGE ON WAREHOUSE SOLAR_WH TO ROLE <USER_OR_ROLE>;
-- GRANT USAGE ON DATABASE SOLAR_DB TO ROLE <USER_OR_ROLE>;
-- GRANT USAGE ON SCHEMA SOLAR_DB.RAW TO ROLE <USER_OR_ROLE>;
-- GRANT USAGE ON SCHEMA SOLAR_DB.MART TO ROLE <USER_OR_ROLE>;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SOLAR_DB.RAW  TO ROLE <USER_OR_ROLE>;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SOLAR_DB.MART TO ROLE <USER_OR_ROLE>;
