USE WAREHOUSE SOLAR_WH;
USE DATABASE SOLAR_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS SOLAR_DB.RAW.SOLAR_OBS (
  OBS_DATE       DATE,
  ZIP            STRING,
  GHI            FLOAT,
  DNI            FLOAT,
  DHI            FLOAT,
  CLOUD_COVER    FLOAT,
  TEMP_C         FLOAT,
  SOURCE         STRING
);

-- Helpful daily aggregate view (optional)
CREATE OR REPLACE VIEW SOLAR_DB.RAW.DAILY_GHI AS
SELECT
  OBS_DATE,
  ZIP,
  AVG(GHI) AS GHI_MEAN
FROM SOLAR_DB.RAW.SOLAR_OBS
GROUP BY OBS_DATE, ZIP;
