USE WAREHOUSE SOLAR_WH;
USE DATABASE SOLAR_DB;
USE SCHEMA MART;

CREATE TABLE IF NOT EXISTS SOLAR_DB.MART.SUMMARIES (
  SUMMARY_DATE   DATE,
  ZIP            STRING,
  SUMMARY_TEXT   STRING,
  CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SOLAR_DB.MART.FORECAST_7D (
  ZIP            STRING,
  FCST_DATE      DATE,
  GHI_PREDICTED  FLOAT,
  METHOD         STRING DEFAULT '7d_ma'
);
