USE WAREHOUSE SOLAR_WH;
USE DATABASE SOLAR_DB;

-- Remove future forecasts from today+1 onward
DELETE FROM SOLAR_DB.MART.FORECAST_7D
WHERE FCST_DATE >= DATEADD(day, 1, CURRENT_DATE());

-- Re-insert 7-day moving-average baseline forecast
INSERT INTO SOLAR_DB.MART.FORECAST_7D (ZIP, FCST_DATE, GHI_PREDICTED, METHOD)
WITH last7 AS (
  SELECT ZIP, AVG(GHI) AS GHI_7D_AVG
  FROM SOLAR_DB.RAW.SOLAR_OBS
  WHERE OBS_DATE >= DATEADD(day, -6, CURRENT_DATE())   -- last 7 days including today
  GROUP BY ZIP
),
dates AS (
  SELECT DATEADD(day, seq4()+1, CURRENT_DATE()) AS FCST_DATE
  FROM TABLE(GENERATOR(ROWCOUNT => 7))
)
SELECT l.ZIP, d.FCST_DATE, l.GHI_7D_AVG AS GHI_PREDICTED, '7d_ma'
FROM last7 l
CROSS JOIN dates d;
