-- 1) Today’s averages (validates /ghitoday)
SELECT ZIP, AVG(GHI) AS GHI_MEAN
FROM SOLAR_DB.RAW.SOLAR_OBS
WHERE OBS_DATE = CURRENT_DATE()
GROUP BY ZIP
ORDER BY ZIP;

-- 2) Summaries table (validates /summaries)
SELECT *
FROM SOLAR_DB.MART.SUMMARIES
WHERE SUMMARY_DATE = CURRENT_DATE()
ORDER BY CREATED_AT DESC;

-- 3) Forecast table (validates /forecast)
SELECT *
FROM SOLAR_DB.MART.FORECAST_7D
ORDER BY ZIP, FCST_DATE;

-- 4) Trend (14 days) for a given ZIP (validates /ghitrend)
-- Replace 93727 if needed
SELECT TO_VARCHAR(OBS_DATE) AS OBS_DATE, AVG(GHI) AS GHI_MEAN
FROM SOLAR_DB.RAW.SOLAR_OBS
WHERE ZIP = '93727'
  AND OBS_DATE >= DATEADD(day, -13, CURRENT_DATE())
GROUP BY OBS_DATE
ORDER BY OBS_DATE;
