USE WAREHOUSE SOLAR_WH;

SHOW WAREHOUSES LIKE 'SOLAR_WH';
SHOW DATABASES LIKE 'SOLAR_DB';
SHOW SCHEMAS IN DATABASE SOLAR_DB;
SHOW TABLES  IN SCHEMA SOLAR_DB.RAW;
SHOW TABLES  IN SCHEMA SOLAR_DB.MART;
SHOW VIEWS   IN SCHEMA SOLAR_DB.MART;
