USE WAREHOUSE SOLAR_WH;
USE DATABASE  SOLAR_DB;
USE SCHEMA    RAW;

-- Delete obvious bad rows (all zeros for today)
DELETE FROM RAW.SOLAR_OBS
WHERE OBS_DATE = CURRENT_DATE()
  AND COALESCE(GHI,0)=0 AND COALESCE(DNI,0)=0 AND COALESCE(DHI,0)=0;

-- Handy checks
SELECT * FROM MART.SUMMARIES
WHERE SUMMARY_DATE = CURRENT_DATE()
ORDER BY CREATED_AT DESC;

SELECT * FROM RAW.SOLAR_OBS
WHERE OBS_DATE = CURRENT_DATE()
ORDER BY INGESTED_AT DESC;
