name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build React (Vite)
        working-directory: react-frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # IMPORTANT: keep the exact secret name SWA gave your repo.
          # Look in your current failing workflow for the real name and paste it below:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_WATER_0C536240F }}
          action: upload
          app_location: "react-frontend"   # where package.json lives
          output_location: "dist"          # Vite build output under react-frontend/dist
          skip_app_build: true             # we already built above
          skip_api_build: true             # API is a separate Function App
