name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: swa-deploy-main
      cancel-in-progress: true
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: react-frontend/package-lock.json

      - name: Build React (Vite)
        working-directory: react-frontend
        run: |
          npm ci
          npm run build
          test -d dist && ls -la dist

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Create a repo secret with this exact name holding your SWA deployment token
          # (GitHub → Repo → Settings → Secrets → Actions)
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: react-frontend
          output_location: dist
          skip_app_build: true
          skip_api_build: true
