name: Deploy Azure Function App

on:
  push:
    branches: [ main ]
    paths:
      - 'azure-functions/**'
      - '.github/workflows/deploy-functions.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Deploy the Functions in the 'azure-functions' folder
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: func-solar-15013
          package: azure-functions
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
